### ISSUE TITLE
Better error messages in rust/diesel

### ISSUE THREAD

**Issue by srhickma** [YugaByte/orm-examples#40]
In many cases, if an error occurs using the rust/diesel example ORM, the cause of the error will not be displayed to the user. Instead the app will panic, displaying something along the lines of: `panicked at 'called "Option::unwrap()" on a "None" value'`. Ideally we should propagate the causes of errors to the api, and display them "nicely" with logging (rather than panics).

**Comment by svranesevic** [comment]
@srhickma Could you please specify the cases I can use for acceptance testing for this issue, thanks.

**Comment by srhickma** [comment]
Hi @svranesevic,

Ideally we should bubble up any `Result` types returned from diesel to the api, and then log these errors at the api level (if an internal error), returning appropriate status codes to the caller. At a minimum, we should differentiate between user errors (e.g. a "not found" error when trying to find a product by id) and internal errors (e.g. database errors). I do not think we have any specific criteria for the error messages we want to display (cc @rkarthik007), so anything that would make it clear to a user the cause of the error should be fine.

**Comment by svranesevic** [comment]
Hi @srhickma,
Could you take a look at https://github.com/YugaByte/orm-examples/pull/45

I do not have permissions to set reviewers, etc. on PRs
