### ISSUE TITLE
first call to the spring app always fails

### ISSUE THREAD

**Issue by schoudhury** [YugaByte/orm-examples#7]
added the instructions to https://docs.yugabyte.com/latest/develop/build-apps/java/ysql-spring-data/

however, the very first curl command to create the first user always fails. retrying the operation succeeds.

**Comment by rkarthik007** [comment]
This is a YSQL issue I think. @m-iancu - I remember you mentioning something about cache consistency for this one. Could you please take a look?

**Comment by srhickma** [comment]
Fixed by https://github.com/YugaByte/yugabyte-db/commit/c7b3b0dae4e17ba56ea3a23e39fc21a474acdf3a. Tested locally with a hikari pool size of 8.
